# Generated by Django 4.0.4 on 2022-06-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_budget_customer_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='has_passed_limit',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
