# Generated by Django 4.0.4 on 2022-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership_history',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
