# Generated by Django 4.0.4 on 2022-05-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deposited', models.IntegerField()),
                ('banking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking_accounts.bankingaccount')),
            ],
        ),
    ]
