# Generated by Django 4.0.4 on 2022-05-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_types.accounttype')),
            ],
        ),
    ]
