# Generated by Django 4.0.4 on 2022-05-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('customers', '0002_alter_customer_membership_history'),
        ('banking_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingaccount',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='bankingaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
