# Generated by Django 4.0.4 on 2022-06-01 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking_accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingaccount',
            name='customer',
        ),
        migrations.AddField(
            model_name='bankingaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
