# Generated by Django 4.0.4 on 2022-06-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_accounts', '0003_remove_bankingaccount_customer_bankingaccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankingaccount',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='bankingaccount',
            name='budget',
        ),
    ]
