# Generated by Django 4.0.4 on 2022-06-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_membership_history'),
        ('budgets', '0001_initial'),
        ('banking_accounts', '0004_rename_user_bankingaccount_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingaccount',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgets.budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingaccount',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
