# Generated by Django 4.0.4 on 2022-06-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_accounts', '0005_bankingaccount_budget_bankingaccount_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingaccount',
            name='customer',
        ),
    ]
