# Generated by Django 4.0.4 on 2022-06-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_accounts', '0007_rename_users_bankingaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingaccount',
            name='account_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
