# Generated by Django 4.0.4 on 2022-06-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_accounts', '0008_bankingaccount_account_name'),
        ('transactions', '0002_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banking_accounts.bankingaccount'),
            preserve_default=False,
        ),
    ]
